version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - yum install -y maven
  build:
    commands:
      - mvn clean install
      - mvn package
      - mkdir output
      - cp target/*.war output/

artifacts:
  files:
    - output/*.war
    - appspec.yml
    - scripts/*
    - install_dependencies.sh
    - start_server.sh
    - stop_server.sh